package QuizGUI;

import java.awt.Color;
import java.util.concurrent.*;
import static java.util.concurrent.TimeUnit.SECONDS;
import java.util.Random;
import javax.swing.JOptionPane;

public class quiz extends javax.swing.JFrame {
    final ScheduledExecutorService scheduler = Executors.newScheduledThreadPool(1);
    /**
     * Creates new form quiz
     */
    int counter = 0;
    boolean done = false; //will be used to check if the user is done answering
    
    Random random=new Random();
        int digit1;
        int digit2;
        int score;
        int maxloop = 15;
        int userAns;
        int correctAns = 0;
        int correct = 0;
        int tride = 0;
        int questionNum;
        String question;
        
    public quiz() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        ON_OFF_Group = new javax.swing.ButtonGroup();
        Questions = new javax.swing.ButtonGroup();
        Type = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        questionTxt = new javax.swing.JLabel();
        AnsTxt = new javax.swing.JTextField();
        pract_btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        random_btn = new javax.swing.JRadioButton();
        btn_1 = new javax.swing.JRadioButton();
        btn_2 = new javax.swing.JRadioButton();
        btn_3 = new javax.swing.JRadioButton();
        btn_4 = new javax.swing.JRadioButton();
        btn_5 = new javax.swing.JRadioButton();
        btn_6 = new javax.swing.JRadioButton();
        btn_7 = new javax.swing.JRadioButton();
        btn_9 = new javax.swing.JRadioButton();
        btn_8 = new javax.swing.JRadioButton();
        check_btn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        ONbtn = new javax.swing.JRadioButton();
        OFFbtn = new javax.swing.JRadioButton();
        time = new javax.swing.JLabel();
        start_btn = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        add_btn = new javax.swing.JCheckBox();
        mult_btn = new javax.swing.JCheckBox();
        sub_btn = new javax.swing.JCheckBox();
        div_btn = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        correct_label = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        tried_label = new javax.swing.JLabel();
        ExitLB = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(168, 218, 242));
        setUndecorated(true);

        jPanel4.setBackground(new java.awt.Color(168, 218, 242));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jPanel5.setBackground(new java.awt.Color(168, 218, 242));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(97, 10, 156), 2, true));

        questionTxt.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        questionTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        AnsTxt.setBackground(new java.awt.Color(168, 218, 242));
        AnsTxt.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        AnsTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AnsTxt.setText("= ??");
        AnsTxt.setBorder(null);
        AnsTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnsTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(questionTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AnsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AnsTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(questionTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pract_btn.setBackground(new java.awt.Color(97, 10, 156));
        pract_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pract_btn.setForeground(new java.awt.Color(255, 255, 255));
        pract_btn.setText("Practice again");
        pract_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pract_btnActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(168, 218, 242));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(97, 10, 156), 2, true));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("No. of Questions");

        random_btn.setBackground(new java.awt.Color(168, 218, 242));
        Questions.add(random_btn);
        random_btn.setText("Random");
        random_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                random_btnActionPerformed(evt);
            }
        });

        btn_1.setBackground(new java.awt.Color(168, 218, 242));
        Questions.add(btn_1);
        btn_1.setText("1");
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });

        btn_2.setBackground(new java.awt.Color(168, 218, 242));
        Questions.add(btn_2);
        btn_2.setText("2");
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });

        btn_3.setBackground(new java.awt.Color(168, 218, 242));
        Questions.add(btn_3);
        btn_3.setText("3");
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });

        btn_4.setBackground(new java.awt.Color(168, 218, 242));
        Questions.add(btn_4);
        btn_4.setText("4");
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });

        btn_5.setBackground(new java.awt.Color(168, 218, 242));
        Questions.add(btn_5);
        btn_5.setText("5");
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });

        btn_6.setBackground(new java.awt.Color(168, 218, 242));
        Questions.add(btn_6);
        btn_6.setText("6");
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });

        btn_7.setBackground(new java.awt.Color(168, 218, 242));
        Questions.add(btn_7);
        btn_7.setText("7");
        btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7ActionPerformed(evt);
            }
        });

        btn_9.setBackground(new java.awt.Color(168, 218, 242));
        Questions.add(btn_9);
        btn_9.setText("9");
        btn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_9ActionPerformed(evt);
            }
        });

        btn_8.setBackground(new java.awt.Color(168, 218, 242));
        Questions.add(btn_8);
        btn_8.setText("8");
        btn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(random_btn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(random_btn)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_1)
                    .addComponent(btn_2)
                    .addComponent(btn_3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_4)
                    .addComponent(btn_5)
                    .addComponent(btn_6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_7)
                    .addComponent(btn_8)
                    .addComponent(btn_9))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        check_btn.setBackground(new java.awt.Color(97, 10, 156));
        check_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        check_btn.setForeground(new java.awt.Color(255, 255, 255));
        check_btn.setText("Check Answer");
        check_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_btnActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(168, 218, 242));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(97, 10, 156), 2, true));

        jLabel8.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Timer");

        ON_OFF_Group.add(ONbtn);
        ONbtn.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        ONbtn.setText("On");

        ON_OFF_Group.add(OFFbtn);
        OFFbtn.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        OFFbtn.setText("Off");

        time.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(OFFbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                                .addComponent(ONbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(ONbtn)
                .addGap(18, 18, 18)
                .addComponent(OFFbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(time, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        start_btn.setBackground(new java.awt.Color(97, 10, 156));
        start_btn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        start_btn.setForeground(new java.awt.Color(255, 255, 255));
        start_btn.setText("Start");
        start_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_btnActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(168, 218, 242));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(97, 10, 156), 2, true));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Type:");

        add_btn.setBackground(new java.awt.Color(168, 218, 242));
        Type.add(add_btn);
        add_btn.setText("Addition");
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });

        mult_btn.setBackground(new java.awt.Color(168, 218, 242));
        Type.add(mult_btn);
        mult_btn.setText("Multiplication");
        mult_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mult_btnActionPerformed(evt);
            }
        });

        sub_btn.setBackground(new java.awt.Color(168, 218, 242));
        Type.add(sub_btn);
        sub_btn.setText("Subtraction");
        sub_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sub_btnActionPerformed(evt);
            }
        });

        div_btn.setBackground(new java.awt.Color(168, 218, 242));
        Type.add(div_btn);
        div_btn.setText("Divison");
        div_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                div_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(div_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mult_btn)
                            .addComponent(sub_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 73, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(add_btn)
                .addGap(18, 18, 18)
                .addComponent(sub_btn)
                .addGap(18, 18, 18)
                .addComponent(div_btn)
                .addGap(18, 18, 18)
                .addComponent(mult_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Tried:");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Correct:");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(168, 218, 242));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(97, 10, 156), 2));

        correct_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        correct_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        correct_label.setText("0");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(correct_label, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(correct_label, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(168, 218, 242));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(97, 10, 156), 2));

        tried_label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tried_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tried_label.setText("0");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tried_label, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tried_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
        );

        ExitLB.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ExitLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ExitLB.setText("X");
        ExitLB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitLBMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(18, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(pract_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(check_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(start_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExitLB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ExitLB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pract_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(check_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(start_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AnsTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnsTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnsTxtActionPerformed

    public void addition()
    {
        AnsTxt.setText("");
        AnsTxt.enableInputMethods(true); 
        digit1 = random.nextInt(10);
        digit2 = random.nextInt(10);
        questionTxt.setText(digit1 +"+"+ digit2); 
    }
    
    public void substraction()
    {
        AnsTxt.setText("");
        AnsTxt.enableInputMethods(true);
        digit1 = random.nextInt(10);
        digit2 = random.nextInt(10);
        questionTxt.setText(digit1 +"-"+ digit2);
    }
    
    public void divison()
    {
        AnsTxt.setText("");
        AnsTxt.enableInputMethods(true);
        digit1 = random.nextInt(10);
        digit2 = random.nextInt(10);
        questionTxt.setText(digit1 +"/"+ digit2);
    }
    
    public void multiplication()
    {
        AnsTxt.setText("");
        AnsTxt.enableInputMethods(true);
        digit1 = random.nextInt(10);
        digit2 = random.nextInt(10);
        questionTxt.setText(digit1 +"x"+ digit2); 
    }
    
    private void start_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start_btnActionPerformed
        // TODO add your handling code here:
        boolean timerOn = ONbtn.isSelected();
        boolean timerOff = OFFbtn.isSelected();
        boolean add = add_btn.isSelected();
        boolean sub = sub_btn.isSelected();
        boolean div = div_btn.isSelected();
        boolean multi = mult_btn.isSelected();
        
        
        if(timerOn==true && (add==true || sub==true || div==true || multi==true) )
        {
            AnsTxt.setText("");
            AnsTxt.enableInputMethods(true);
            start_btn.setVisible(false);
            pract_btn.setVisible(false);
            final ScheduledExecutorService scheduler = Executors.newScheduledThreadPool(1);

            final Runnable runnable = new Runnable() 
            {
                int countdownStarter = 30;

                public void run() 
                {
                    if(done == false)
                    {
                        time.setText(String.valueOf(countdownStarter));
                        countdownStarter--;

                        if (countdownStarter < 15) 
                        {
                            time.setForeground(Color.red);
                        }

                        else
                        {
                            time.setForeground(Color.black);
                        }

                        if (countdownStarter <= 0) 
                        {
                            time.setForeground(Color.black);
                            time.setText("0");
                            JOptionPane.showMessageDialog(null,"Time is Up!");
                            pract_btn.setVisible(true);
                            scheduler.shutdown();
                            questionTxt.setText(null);
                            AnsTxt.setText(null);
                        }
                    }
                    
                    else if(done == true)
                    {
                        time.setText("");
                    }
                }
            };
        scheduler.scheduleAtFixedRate(runnable, 0, 1, SECONDS);
        }
        
        else if(timerOff==true && (add==true || sub==true || div==true || multi==true) )
        {
            AnsTxt.setText("");
            AnsTxt.enableInputMethods(true);
            start_btn.setVisible(false);
            time.setText("Timer is Off");
        }
        
        else if(timerOff == false && timerOn== false)
        {
            JOptionPane.showMessageDialog(null,"Please turn the timer either on or off");
        }
    }//GEN-LAST:event_start_btnActionPerformed
    
    private void check_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_btnActionPerformed
        // TODO add your handling code here:
        //wait for userinput then calculate
        if (add_btn.isSelected())
        {
            while( counter <= questionNum)
            {
                correctAns = digit1 + digit2;
                String answer = AnsTxt.getText();
                userAns = Integer.parseInt(answer);
                
                if(correctAns == userAns)
                {
                    JOptionPane.showMessageDialog(null,"Correct");
                    correct++;
                    correct_label.setText(String.valueOf(correct));
                    tride++;
                    tried_label.setText(String.valueOf(tride));
                    
                    if(counter == questionNum)
                    {
                        JOptionPane.showMessageDialog(null,"All Quiz Questions have been answered");
                        JOptionPane.showMessageDialog(null,"Quiz is over");
                        done = true;
                        System.out.println(done);
                        time.setVisible(false);
                        scheduler.shutdown();
                        pract_btn.setVisible(true);
                        break;
                    }
                }

                else if(correctAns != userAns)
                {
                    JOptionPane.showMessageDialog(null,"Wrong");
                    tride++;
                    tried_label.setText(String.valueOf(tride));
                    
                    if(counter == questionNum)
                    {
                        JOptionPane.showMessageDialog(null,"All Quiz Questions have been answered");
                        JOptionPane.showMessageDialog(null,"Quiz is over");
                        done = true;
                        time.setVisible(false);
                        scheduler.shutdown();
                        pract_btn.setVisible(true);
                        break;
                    }
                }
                counter++;
                addition();
                break;
            }
            
        }
        
        if (sub_btn.isSelected())
        {
            while( counter <= questionNum)
            {
                correctAns = digit1 - digit2;
                String answer = AnsTxt.getText();
                userAns = Integer.parseInt(answer);
                
                if(correctAns == userAns)
                {
                    JOptionPane.showMessageDialog(null,"Correct");
                    correct++;
                    correct_label.setText(String.valueOf(correct));
                    tride++;
                    tried_label.setText(String.valueOf(tride));
                    
                    if(counter == questionNum)
                    {
                        JOptionPane.showMessageDialog(null,"All Quiz Questions have been answered");
                        JOptionPane.showMessageDialog(null,"Quiz is over");
                        done = true;
                        time.setVisible(false);
                        scheduler.shutdown();
                        pract_btn.setVisible(true);
                        break;
                    }
                }

                else if(correctAns != userAns)
                {
                    JOptionPane.showMessageDialog(null,"Wrong");
                    tride++;
                    tried_label.setText(String.valueOf(tride));
                    
                    if(counter == questionNum)
                    {
                        JOptionPane.showMessageDialog(null,"All Quiz Questions have been answered");
                        JOptionPane.showMessageDialog(null,"Quiz is over");
                        done = true;
                        time.setVisible(false);
                        scheduler.shutdown();
                        pract_btn.setVisible(true);
                        break;
                    }
                }
                counter++;
                substraction();
                break;
            }
        }
        
        if (div_btn.isSelected())
        {
            while( counter <= questionNum)
            {
                correctAns = digit1 / digit2;
                String answer = AnsTxt.getText();
                userAns = Integer.parseInt(answer);
                
                if(correctAns == userAns)
                {
                    JOptionPane.showMessageDialog(null,"Correct");
                    correct++;
                    correct_label.setText(String.valueOf(correct));
                    tride++;
                    tried_label.setText(String.valueOf(tride));
                    
                    if(counter == questionNum)
                    {
                        JOptionPane.showMessageDialog(null,"All Quiz Questions have been answered");
                        JOptionPane.showMessageDialog(null,"Quiz is over");
                        done = true;
                        time.setVisible(false);
                        scheduler.shutdown();
                        pract_btn.setVisible(true);
                        break;
                    }
                }

                else if(correctAns != userAns)
                {
                    JOptionPane.showMessageDialog(null,"Wrong");
                    tride++;
                    tried_label.setText(String.valueOf(tride));
                    
                    if(counter == questionNum)
                    {
                        JOptionPane.showMessageDialog(null,"All Quiz Questions have been answered");
                        JOptionPane.showMessageDialog(null,"Quiz is over");
                        done = true;
                        time.setVisible(false);
                        scheduler.shutdown();
                        pract_btn.setVisible(true);
                        break;
                    }
                }
                counter++;
                divison();
                break;
            }
        }
        
        if (mult_btn.isSelected())
        {
            while( counter <= questionNum)
            {
                correctAns = digit1 * digit2;
                String answer = AnsTxt.getText();
                userAns = Integer.parseInt(answer);
                
                if(correctAns == userAns)
                {
                    JOptionPane.showMessageDialog(null,"Correct");
                    correct++;
                    correct_label.setText(String.valueOf(correct));
                    tride++;
                    tried_label.setText(String.valueOf(tride));
                    
                    if(counter == questionNum)
                    {
                        JOptionPane.showMessageDialog(null,"All Quiz Questions have been answered");
                        JOptionPane.showMessageDialog(null,"Quiz is over");
                        done = true;
                        time.setVisible(false);
                        scheduler.shutdown();
                        pract_btn.setVisible(true);
                        break;
                    }
                }

                else if(correctAns != userAns)
                {
                    JOptionPane.showMessageDialog(null,"Wrong");
                    tride++;
                    tried_label.setText(String.valueOf(tride));
                    
                    if(counter == questionNum)
                    {
                        JOptionPane.showMessageDialog(null,"All Quiz Questions have been answered");
                        JOptionPane.showMessageDialog(null,"Quiz is over");
                        done = true;
                        time.setVisible(false);
                        scheduler.shutdown();
                        pract_btn.setVisible(true);
                        break;
                    }
                }
                counter++;
                multiplication();
                break;
            }
        }
        
    }//GEN-LAST:event_check_btnActionPerformed

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        // TODO add your handling code here:
        addition();
    }//GEN-LAST:event_add_btnActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
        // TODO add your handling code here:
        questionNum = 1;
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
        // TODO add your handling code here:
        questionNum = 0;
    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
        // TODO add your handling code here:
        questionNum = 2;
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
        // TODO add your handling code here:
        questionNum = 3;
    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
        // TODO add your handling code here:
        questionNum = 4;
    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
        // TODO add your handling code here:
        questionNum = 5;
    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
        // TODO add your handling code here:
        questionNum = 6;
    }//GEN-LAST:event_btn_7ActionPerformed

    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
        // TODO add your handling code here:
        questionNum = 7;
    }//GEN-LAST:event_btn_8ActionPerformed

    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
        // TODO add your handling code here:
        questionNum = 8;
    }//GEN-LAST:event_btn_9ActionPerformed

    private void random_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_random_btnActionPerformed
        // TODO add your handling code here:
        questionNum = 14;
    }//GEN-LAST:event_random_btnActionPerformed

    private void sub_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sub_btnActionPerformed
        // TODO add your handling code here:
        substraction();
    }//GEN-LAST:event_sub_btnActionPerformed

    private void div_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_div_btnActionPerformed
        // TODO add your handling code here:
        divison();
    }//GEN-LAST:event_div_btnActionPerformed

    private void mult_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mult_btnActionPerformed
        // TODO add your handling code here:
        multiplication();
    }//GEN-LAST:event_mult_btnActionPerformed

    private void pract_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pract_btnActionPerformed
        // TODO add your handling code here:
        new quiz().setVisible(true);
        this.setVisible(false);
            
    }//GEN-LAST:event_pract_btnActionPerformed

    private void ExitLBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitLBMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitLBMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AnsTxt;
    private javax.swing.JLabel ExitLB;
    private javax.swing.JRadioButton OFFbtn;
    private javax.swing.ButtonGroup ON_OFF_Group;
    private javax.swing.JRadioButton ONbtn;
    private javax.swing.ButtonGroup Questions;
    private javax.swing.ButtonGroup Type;
    private javax.swing.JCheckBox add_btn;
    private javax.swing.JRadioButton btn_1;
    private javax.swing.JRadioButton btn_2;
    private javax.swing.JRadioButton btn_3;
    private javax.swing.JRadioButton btn_4;
    private javax.swing.JRadioButton btn_5;
    private javax.swing.JRadioButton btn_6;
    private javax.swing.JRadioButton btn_7;
    private javax.swing.JRadioButton btn_8;
    private javax.swing.JRadioButton btn_9;
    private javax.swing.JButton check_btn;
    private javax.swing.JLabel correct_label;
    private javax.swing.JCheckBox div_btn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JCheckBox mult_btn;
    private javax.swing.JButton pract_btn;
    private javax.swing.JLabel questionTxt;
    private javax.swing.JRadioButton random_btn;
    private javax.swing.JButton start_btn;
    private javax.swing.JCheckBox sub_btn;
    private javax.swing.JLabel time;
    private javax.swing.JLabel tried_label;
    // End of variables declaration//GEN-END:variables
}
