/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculator;

/**
 *
 * @author gomim
 */
public class Calculator extends javax.swing.JFrame {

    double firstNum;
    double secondNum;
    double result;
    String operation;
    
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CalculatorPane = new javax.swing.JPanel();
        displayPane = new javax.swing.JPanel();
        input = new javax.swing.JLabel();
        resutlsDisplay = new javax.swing.JLabel();
        clearPanel = new javax.swing.JPanel();
        clearBtn = new javax.swing.JLabel();
        BackspacePanel = new javax.swing.JPanel();
        backspaceBtn = new javax.swing.JLabel();
        PercentPanle = new javax.swing.JPanel();
        percentBtn = new javax.swing.JLabel();
        divisonPanel = new javax.swing.JPanel();
        divBtn = new javax.swing.JLabel();
        MultificationPanel = new javax.swing.JPanel();
        multiBtn = new javax.swing.JLabel();
        SubtractionPanel = new javax.swing.JPanel();
        subBtn = new javax.swing.JLabel();
        AdditonPanel = new javax.swing.JPanel();
        addBtn = new javax.swing.JLabel();
        EqualPanel = new javax.swing.JPanel();
        equalBtn = new javax.swing.JLabel();
        No7_Panel = new javax.swing.JPanel();
        Btn7 = new javax.swing.JLabel();
        No8_Panel = new javax.swing.JPanel();
        Btn8 = new javax.swing.JLabel();
        No9_Panel = new javax.swing.JPanel();
        Btn9 = new javax.swing.JLabel();
        No4_Panel = new javax.swing.JPanel();
        Btn4 = new javax.swing.JLabel();
        No5_Panel = new javax.swing.JPanel();
        Btn5 = new javax.swing.JLabel();
        No6_Panel = new javax.swing.JPanel();
        Btn6 = new javax.swing.JLabel();
        No1_Panel = new javax.swing.JPanel();
        Btn1 = new javax.swing.JLabel();
        No2_Panel = new javax.swing.JPanel();
        Btn2 = new javax.swing.JLabel();
        No3_Panel = new javax.swing.JPanel();
        Btn3 = new javax.swing.JLabel();
        ModulusPanel = new javax.swing.JPanel();
        modBtn = new javax.swing.JLabel();
        zeroPanel = new javax.swing.JPanel();
        Btn0 = new javax.swing.JLabel();
        PointPanel = new javax.swing.JPanel();
        pointBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setResizable(false);

        CalculatorPane.setBackground(new java.awt.Color(255, 255, 255));

        displayPane.setBackground(new java.awt.Color(255, 255, 255));
        displayPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        input.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        input.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        resutlsDisplay.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        resutlsDisplay.setForeground(new java.awt.Color(204, 204, 204));
        resutlsDisplay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout displayPaneLayout = new javax.swing.GroupLayout(displayPane);
        displayPane.setLayout(displayPaneLayout);
        displayPaneLayout.setHorizontalGroup(
            displayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(displayPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(displayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, displayPaneLayout.createSequentialGroup()
                        .addGap(0, 327, Short.MAX_VALUE)
                        .addComponent(resutlsDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(input, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE))
                .addContainerGap())
        );
        displayPaneLayout.setVerticalGroup(
            displayPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, displayPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resutlsDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(input, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );

        clearPanel.setPreferredSize(new java.awt.Dimension(90, 90));

        clearBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        clearBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clearBtn.setText("Clear");
        clearBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout clearPanelLayout = new javax.swing.GroupLayout(clearPanel);
        clearPanel.setLayout(clearPanelLayout);
        clearPanelLayout.setHorizontalGroup(
            clearPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clearPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clearBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addContainerGap())
        );
        clearPanelLayout.setVerticalGroup(
            clearPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clearPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clearBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addContainerGap())
        );

        BackspacePanel.setPreferredSize(new java.awt.Dimension(90, 90));
        BackspacePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackspacePanelMouseClicked(evt);
            }
        });

        backspaceBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backspaceBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backspaceBtn.setText("<<<");
        backspaceBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backspaceBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BackspacePanelLayout = new javax.swing.GroupLayout(BackspacePanel);
        BackspacePanel.setLayout(BackspacePanelLayout);
        BackspacePanelLayout.setHorizontalGroup(
            BackspacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackspacePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backspaceBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addContainerGap())
        );
        BackspacePanelLayout.setVerticalGroup(
            BackspacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackspacePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backspaceBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addContainerGap())
        );

        PercentPanle.setPreferredSize(new java.awt.Dimension(90, 90));

        percentBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        percentBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        percentBtn.setText("%");
        percentBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                percentBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PercentPanleLayout = new javax.swing.GroupLayout(PercentPanle);
        PercentPanle.setLayout(PercentPanleLayout);
        PercentPanleLayout.setHorizontalGroup(
            PercentPanleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PercentPanleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(percentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addContainerGap())
        );
        PercentPanleLayout.setVerticalGroup(
            PercentPanleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PercentPanleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(percentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addContainerGap())
        );

        divisonPanel.setPreferredSize(new java.awt.Dimension(90, 90));

        divBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        divBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        divBtn.setText("/");
        divBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                divBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout divisonPanelLayout = new javax.swing.GroupLayout(divisonPanel);
        divisonPanel.setLayout(divisonPanelLayout);
        divisonPanelLayout.setHorizontalGroup(
            divisonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(divisonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(divBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addContainerGap())
        );
        divisonPanelLayout.setVerticalGroup(
            divisonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(divisonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(divBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addContainerGap())
        );

        MultificationPanel.setPreferredSize(new java.awt.Dimension(90, 90));

        multiBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        multiBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        multiBtn.setText("X");
        multiBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                multiBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MultificationPanelLayout = new javax.swing.GroupLayout(MultificationPanel);
        MultificationPanel.setLayout(MultificationPanelLayout);
        MultificationPanelLayout.setHorizontalGroup(
            MultificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MultificationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(multiBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MultificationPanelLayout.setVerticalGroup(
            MultificationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MultificationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(multiBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SubtractionPanel.setPreferredSize(new java.awt.Dimension(90, 90));

        subBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        subBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subBtn.setText("-");
        subBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SubtractionPanelLayout = new javax.swing.GroupLayout(SubtractionPanel);
        SubtractionPanel.setLayout(SubtractionPanelLayout);
        SubtractionPanelLayout.setHorizontalGroup(
            SubtractionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubtractionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SubtractionPanelLayout.setVerticalGroup(
            SubtractionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SubtractionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(subBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AdditonPanel.setPreferredSize(new java.awt.Dimension(90, 90));

        addBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addBtn.setText("+");
        addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout AdditonPanelLayout = new javax.swing.GroupLayout(AdditonPanel);
        AdditonPanel.setLayout(AdditonPanelLayout);
        AdditonPanelLayout.setHorizontalGroup(
            AdditonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdditonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AdditonPanelLayout.setVerticalGroup(
            AdditonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdditonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        EqualPanel.setPreferredSize(new java.awt.Dimension(90, 90));

        equalBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        equalBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        equalBtn.setText("=");
        equalBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                equalBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout EqualPanelLayout = new javax.swing.GroupLayout(EqualPanel);
        EqualPanel.setLayout(EqualPanelLayout);
        EqualPanelLayout.setHorizontalGroup(
            EqualPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EqualPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(equalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EqualPanelLayout.setVerticalGroup(
            EqualPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EqualPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(equalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        No7_Panel.setPreferredSize(new java.awt.Dimension(90, 90));

        Btn7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Btn7.setText("7");
        Btn7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout No7_PanelLayout = new javax.swing.GroupLayout(No7_Panel);
        No7_Panel.setLayout(No7_PanelLayout);
        No7_PanelLayout.setHorizontalGroup(
            No7_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(No7_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btn7, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addContainerGap())
        );
        No7_PanelLayout.setVerticalGroup(
            No7_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(No7_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btn7, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addContainerGap())
        );

        No8_Panel.setPreferredSize(new java.awt.Dimension(90, 90));

        Btn8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Btn8.setText("8");
        Btn8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout No8_PanelLayout = new javax.swing.GroupLayout(No8_Panel);
        No8_Panel.setLayout(No8_PanelLayout);
        No8_PanelLayout.setHorizontalGroup(
            No8_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(No8_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        No8_PanelLayout.setVerticalGroup(
            No8_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(No8_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        No9_Panel.setPreferredSize(new java.awt.Dimension(90, 90));

        Btn9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Btn9.setText("9");
        Btn9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout No9_PanelLayout = new javax.swing.GroupLayout(No9_Panel);
        No9_Panel.setLayout(No9_PanelLayout);
        No9_PanelLayout.setHorizontalGroup(
            No9_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(No9_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        No9_PanelLayout.setVerticalGroup(
            No9_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(No9_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        No4_Panel.setPreferredSize(new java.awt.Dimension(90, 90));

        Btn4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Btn4.setText("4");
        Btn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout No4_PanelLayout = new javax.swing.GroupLayout(No4_Panel);
        No4_Panel.setLayout(No4_PanelLayout);
        No4_PanelLayout.setHorizontalGroup(
            No4_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(No4_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        No4_PanelLayout.setVerticalGroup(
            No4_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(No4_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        No5_Panel.setPreferredSize(new java.awt.Dimension(90, 90));

        Btn5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Btn5.setText("5");
        Btn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout No5_PanelLayout = new javax.swing.GroupLayout(No5_Panel);
        No5_Panel.setLayout(No5_PanelLayout);
        No5_PanelLayout.setHorizontalGroup(
            No5_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(No5_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        No5_PanelLayout.setVerticalGroup(
            No5_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(No5_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        No6_Panel.setPreferredSize(new java.awt.Dimension(90, 90));

        Btn6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Btn6.setText("6");
        Btn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout No6_PanelLayout = new javax.swing.GroupLayout(No6_Panel);
        No6_Panel.setLayout(No6_PanelLayout);
        No6_PanelLayout.setHorizontalGroup(
            No6_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(No6_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        No6_PanelLayout.setVerticalGroup(
            No6_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(No6_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        No1_Panel.setPreferredSize(new java.awt.Dimension(90, 90));

        Btn1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Btn1.setText("1");
        Btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout No1_PanelLayout = new javax.swing.GroupLayout(No1_Panel);
        No1_Panel.setLayout(No1_PanelLayout);
        No1_PanelLayout.setHorizontalGroup(
            No1_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(No1_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btn1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addContainerGap())
        );
        No1_PanelLayout.setVerticalGroup(
            No1_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(No1_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btn1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addContainerGap())
        );

        No2_Panel.setPreferredSize(new java.awt.Dimension(90, 90));

        Btn2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Btn2.setText("2");
        Btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout No2_PanelLayout = new javax.swing.GroupLayout(No2_Panel);
        No2_Panel.setLayout(No2_PanelLayout);
        No2_PanelLayout.setHorizontalGroup(
            No2_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(No2_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        No2_PanelLayout.setVerticalGroup(
            No2_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(No2_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        No3_Panel.setPreferredSize(new java.awt.Dimension(90, 90));

        Btn3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Btn3.setText("3");
        Btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout No3_PanelLayout = new javax.swing.GroupLayout(No3_Panel);
        No3_Panel.setLayout(No3_PanelLayout);
        No3_PanelLayout.setHorizontalGroup(
            No3_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(No3_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        No3_PanelLayout.setVerticalGroup(
            No3_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(No3_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ModulusPanel.setPreferredSize(new java.awt.Dimension(90, 90));

        modBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        modBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        modBtn.setText("+/-");
        modBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ModulusPanelLayout = new javax.swing.GroupLayout(ModulusPanel);
        ModulusPanel.setLayout(ModulusPanelLayout);
        ModulusPanelLayout.setHorizontalGroup(
            ModulusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModulusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(modBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ModulusPanelLayout.setVerticalGroup(
            ModulusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModulusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(modBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        zeroPanel.setPreferredSize(new java.awt.Dimension(90, 90));

        Btn0.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Btn0.setText("0");
        Btn0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn0MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout zeroPanelLayout = new javax.swing.GroupLayout(zeroPanel);
        zeroPanel.setLayout(zeroPanelLayout);
        zeroPanelLayout.setHorizontalGroup(
            zeroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zeroPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btn0, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addContainerGap())
        );
        zeroPanelLayout.setVerticalGroup(
            zeroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(zeroPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btn0, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                .addContainerGap())
        );

        PointPanel.setPreferredSize(new java.awt.Dimension(90, 90));

        pointBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pointBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pointBtn.setText(".");
        pointBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pointBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PointPanelLayout = new javax.swing.GroupLayout(PointPanel);
        PointPanel.setLayout(PointPanelLayout);
        PointPanelLayout.setHorizontalGroup(
            PointPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PointPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pointBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PointPanelLayout.setVerticalGroup(
            PointPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PointPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pointBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout CalculatorPaneLayout = new javax.swing.GroupLayout(CalculatorPane);
        CalculatorPane.setLayout(CalculatorPaneLayout);
        CalculatorPaneLayout.setHorizontalGroup(
            CalculatorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalculatorPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(CalculatorPaneLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(CalculatorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clearPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(No7_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(No4_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(No1_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModulusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(CalculatorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CalculatorPaneLayout.createSequentialGroup()
                        .addComponent(zeroPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PointPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CalculatorPaneLayout.createSequentialGroup()
                        .addComponent(No2_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(No3_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CalculatorPaneLayout.createSequentialGroup()
                        .addComponent(BackspacePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addComponent(PercentPanle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CalculatorPaneLayout.createSequentialGroup()
                        .addComponent(No5_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(No6_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CalculatorPaneLayout.createSequentialGroup()
                        .addComponent(No8_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(No9_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(CalculatorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MultificationPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divisonPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubtractionPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdditonPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EqualPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        CalculatorPaneLayout.setVerticalGroup(
            CalculatorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CalculatorPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(displayPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(CalculatorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clearPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackspacePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PercentPanle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divisonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(CalculatorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CalculatorPaneLayout.createSequentialGroup()
                        .addComponent(MultificationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(SubtractionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CalculatorPaneLayout.createSequentialGroup()
                        .addGroup(CalculatorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(No7_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(No8_Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(CalculatorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(No5_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(No4_Panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(CalculatorPaneLayout.createSequentialGroup()
                        .addComponent(No9_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(No6_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(CalculatorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(No1_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(No2_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(No3_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AdditonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(CalculatorPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ModulusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zeroPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PointPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EqualPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CalculatorPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CalculatorPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clearBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBtnMouseClicked
        // TODO add your handling code here:
        input.setText(" ");
        resutlsDisplay.setText(" ");
    }//GEN-LAST:event_clearBtnMouseClicked

    private void Btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn1MouseClicked
        // TODO add your handling code here:
        input.setText(input.getText()+"1");
        resutlsDisplay.setText(resutlsDisplay.getText()+"1");
    }//GEN-LAST:event_Btn1MouseClicked

    private void Btn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn2MouseClicked
        // TODO add your handling code here:
        input.setText(input.getText()+"2");
        resutlsDisplay.setText(resutlsDisplay.getText()+"2");
    }//GEN-LAST:event_Btn2MouseClicked

    private void Btn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn3MouseClicked
        // TODO add your handling code here:
        input.setText(input.getText()+"3");
        resutlsDisplay.setText(resutlsDisplay.getText()+"3");
    }//GEN-LAST:event_Btn3MouseClicked

    private void Btn4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn4MouseClicked
        // TODO add your handling code here:
        input.setText(input.getText()+"4");
        resutlsDisplay.setText(resutlsDisplay.getText()+"4");
    }//GEN-LAST:event_Btn4MouseClicked

    private void Btn5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn5MouseClicked
        // TODO add your handling code here:
        input.setText(input.getText()+"5");
        resutlsDisplay.setText(resutlsDisplay.getText()+"5");
    }//GEN-LAST:event_Btn5MouseClicked

    private void Btn6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn6MouseClicked
        // TODO add your handling code here:
        input.setText(input.getText()+"6");
        resutlsDisplay.setText(resutlsDisplay.getText()+"6");
    }//GEN-LAST:event_Btn6MouseClicked

    private void Btn7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn7MouseClicked
        // TODO add your handling code here:
        input.setText(input.getText()+"7");
        resutlsDisplay.setText(resutlsDisplay.getText()+"7");
    }//GEN-LAST:event_Btn7MouseClicked

    private void Btn8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn8MouseClicked
        // TODO add your handling code here:
        input.setText(input.getText()+"8");
        resutlsDisplay.setText(resutlsDisplay.getText()+"8");
    }//GEN-LAST:event_Btn8MouseClicked

    private void Btn9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn9MouseClicked
        // TODO add your handling code here:
        input.setText(input.getText()+"9");
        resutlsDisplay.setText(resutlsDisplay.getText()+"9");
    }//GEN-LAST:event_Btn9MouseClicked

    private void Btn0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn0MouseClicked
        // TODO add your handling code here:
        input.setText(input.getText()+"0");
        resutlsDisplay.setText(resutlsDisplay.getText()+"0");
    }//GEN-LAST:event_Btn0MouseClicked

    private void divBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divBtnMouseClicked
        // TODO add your handling code here:
        firstNum = Double.parseDouble(input.getText());
        input.setText("");
        resutlsDisplay.setText(resutlsDisplay.getText()+"/");
        operation="/";
    }//GEN-LAST:event_divBtnMouseClicked

    private void multiBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiBtnMouseClicked
        // TODO add your handling code here:
        firstNum = Double.parseDouble(input.getText());
        input.setText("");
        resutlsDisplay.setText(resutlsDisplay.getText()+"x");
        operation="x";
    }//GEN-LAST:event_multiBtnMouseClicked

    private void subBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subBtnMouseClicked
        // TODO add your handling code here:
        firstNum = Double.parseDouble(input.getText());
        input.setText("");
        resutlsDisplay.setText(resutlsDisplay.getText()+"-");
        operation="-";
    }//GEN-LAST:event_subBtnMouseClicked

    private void addBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseClicked
        // TODO add your handling code here:
        firstNum = Double.parseDouble(input.getText());
        input.setText("");
        resutlsDisplay.setText(resutlsDisplay.getText()+"+");
        operation="+";
    }//GEN-LAST:event_addBtnMouseClicked

    private void equalBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_equalBtnMouseClicked
        // TODO add your handling code here:
        String ans;
        
        secondNum = Double.parseDouble(input.getText());
        switch(operation)
        {
            case "+":
                result = firstNum + secondNum;
                ans = String.valueOf(result);
                resutlsDisplay.setText(null);
                input.setText(ans);
                break;
            
            case "-":
                result = firstNum - secondNum;
                ans = String.valueOf(result);
                resutlsDisplay.setText(null);
                input.setText(ans);
                break;
            
            case "x":
                result = firstNum * secondNum;
                ans = String.valueOf(result);
                resutlsDisplay.setText(null);
                input.setText(ans);
                break;
                
            case "/":
                if(secondNum == 0)
                {
                    resutlsDisplay.setText(null);
                    input.setText("ERROR!!");
                }
                
                else
                {
                    result = firstNum / secondNum;
                    ans = String.valueOf(result);
                    resutlsDisplay.setText(null);
                    input.setText(ans);
                }
                break;
                
            case "%":
                result = (firstNum / 100) * secondNum;
                ans = String.valueOf(result);
                resutlsDisplay.setText(null);
                input.setText(ans);
                break;
                    
        }
        
        
    }//GEN-LAST:event_equalBtnMouseClicked

    private void percentBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_percentBtnMouseClicked
        // TODO add your handling code here:
        firstNum = Double.parseDouble(input.getText());
        String firstnum_text = String.valueOf(firstNum);
        input.setText("");
        resutlsDisplay.setText(firstnum_text + "%");
        operation="%";
    }//GEN-LAST:event_percentBtnMouseClicked

    private void modBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modBtnMouseClicked
        // TODO add your handling code here:
        firstNum = Double.parseDouble(input.getText());
        firstNum = firstNum * (-1);
        input.setText(String.valueOf(Math.round(firstNum)));
        resutlsDisplay.setText(String.valueOf(Math.round(firstNum)));
    }//GEN-LAST:event_modBtnMouseClicked

    private void pointBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pointBtnMouseClicked
        // TODO add your handling code here:
        if(!".".equals(input.getText()))
        {
            input.setText(input.getText()+".");
            resutlsDisplay.setText(resutlsDisplay.getText()+".");
        }
        
    }//GEN-LAST:event_pointBtnMouseClicked

    private void BackspacePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackspacePanelMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BackspacePanelMouseClicked

    private void backspaceBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backspaceBtnMouseClicked
        // TODO add your handling code here:
        String backspace = null;
        
        if(input.getText().length()> 0 & resutlsDisplay.getText().length() > 0)
        {
            StringBuilder strB_I = new StringBuilder(input.getText());
            strB_I.deleteCharAt(input.getText().length() - 1);
            backspace = strB_I.toString();
            input.setText(backspace);
            
            StringBuilder strB_R = new StringBuilder(resutlsDisplay.getText());
            strB_R.deleteCharAt(resutlsDisplay.getText().length() - 1);
            backspace = strB_R.toString();
            resutlsDisplay.setText(backspace);
        }
    }//GEN-LAST:event_backspaceBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdditonPanel;
    private javax.swing.JPanel BackspacePanel;
    private javax.swing.JLabel Btn0;
    private javax.swing.JLabel Btn1;
    private javax.swing.JLabel Btn2;
    private javax.swing.JLabel Btn3;
    private javax.swing.JLabel Btn4;
    private javax.swing.JLabel Btn5;
    private javax.swing.JLabel Btn6;
    private javax.swing.JLabel Btn7;
    private javax.swing.JLabel Btn8;
    private javax.swing.JLabel Btn9;
    private javax.swing.JPanel CalculatorPane;
    private javax.swing.JPanel EqualPanel;
    private javax.swing.JPanel ModulusPanel;
    private javax.swing.JPanel MultificationPanel;
    private javax.swing.JPanel No1_Panel;
    private javax.swing.JPanel No2_Panel;
    private javax.swing.JPanel No3_Panel;
    private javax.swing.JPanel No4_Panel;
    private javax.swing.JPanel No5_Panel;
    private javax.swing.JPanel No6_Panel;
    private javax.swing.JPanel No7_Panel;
    private javax.swing.JPanel No8_Panel;
    private javax.swing.JPanel No9_Panel;
    private javax.swing.JPanel PercentPanle;
    private javax.swing.JPanel PointPanel;
    private javax.swing.JPanel SubtractionPanel;
    private javax.swing.JLabel addBtn;
    private javax.swing.JLabel backspaceBtn;
    private javax.swing.JLabel clearBtn;
    private javax.swing.JPanel clearPanel;
    private javax.swing.JPanel displayPane;
    private javax.swing.JLabel divBtn;
    private javax.swing.JPanel divisonPanel;
    private javax.swing.JLabel equalBtn;
    private javax.swing.JLabel input;
    private javax.swing.JLabel modBtn;
    private javax.swing.JLabel multiBtn;
    private javax.swing.JLabel percentBtn;
    private javax.swing.JLabel pointBtn;
    private javax.swing.JLabel resutlsDisplay;
    private javax.swing.JLabel subBtn;
    private javax.swing.JPanel zeroPanel;
    // End of variables declaration//GEN-END:variables
}
